version: "3"

services:
  ghost:
    image: seeruk/ghost:latest
    environment:
    - GHOST_DB=mysql
    - GHOST_DB_HOST=db.docker
    - GHOST_DB_PORT=3306
    - GHOST_DB_USER=ghost
    - GHOST_DB_PASS=ghost
    - GHOST_DB_NAME=ghost
    - GHOST_ENV=development
    - GHOST_VERSION=1.10.0
    # - GHOST_UID=1000
    # - GHOST_GID=1000
    links:
    - mysql:db.docker
    ports:
    - 2368:2368
    volumes:
    - ghostdata:/opt/ghost/home
    - ./dist:/opt/ghost/content/themes/ghost-seer

  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=ghost
    - MYSQL_USER=ghost
    - MYSQL_PASSWORD=ghost
    - MYSQL_DATABASE=ghost
    ports:
    - 3316:3306
    volumes:
    - mysqldata:/var/lib/mysql

volumes:
  ghostdata:
    driver: local
  mysqldata:
    driver: local
